---
- hosts: all
  sudo: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Aktualizuj cache apt, jesli konieczne
      apt: update_cache=yes cache_valid_time=3600

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted

  tasks:
    - name: Pobierz soft z repo apt.
      apt: "name={{ item }} state=present"
      with_items:
        - python-apt
        - python-pycurl

    - name: Instalacja svn.
      tags: debs
      action: apt pkg={{ item }} state=installed
      with_items:
        - subversion
  

    - name: Dodaj repo ondrej dla pozniejszych wersji PHP.
      apt_repository: repo='ppa:ondrej/php' update_cache=yes

    - name: "Instalacja Apache, MySQL, PHP, i dodatkowych programow."
      apt: "name={{ item }} state=present"
      with_items:
        - git
        - curl
        - unzip
        - sendmail
        - apache2
        - php7.1-common
        - php7.1-cli
        - php7.1-dev
        - php7.1-gd
        - php7.1-curl
        - php7.1-json
        - php7.1-xml
        - php7.1-mbstring
        - php7.1-pdo
        - php7.1-mysql
        - php-apcu
        - libpcre3-dev
        - libapache2-mod-php7.1
        - python-mysqldb
        - mysql-server

    - name: Wylacz tymczasowo firewalla.
      service: name=ufw state=stopped

    - name: "Start Apache, MySQL i PHP."
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - apache2
        - mysql

    - name: Uruchom modul rewrite Apache.
      apache2_module: name=rewrite state=present
      notify: restart apache

    - name: Dodaj Apache virtualhost dla Wordpressa.
      template:
        src: "przyklad/wordpress.dev.conf.j2"
        dest: "/etc/apache2/sites-available/{{ domain }}.dev.conf"
        owner: root
        group: root
        mode: 0644
   #   notify: restart apache

    - name: Symlink Wordpress virtualhost czy aktywny.
      file:
        src: "/etc/apache2/sites-available/{{ domain }}.dev.conf"
        dest: "/etc/apache2/sites-enabled/{{ domain }}.dev.conf"
        state: link
      notify: restart apache

    - name: Usun domyslny plik virtualhost.
      file:
        path: "/etc/apache2/sites-enabled/000-default.conf"
        state: absent
     # notify: restart apache

    - name: Dostosuj ustawienia pamieci OpCache.
      lineinfile:
        dest: "/etc/php/7.1/apache2/conf.d/10-opcache.ini"
        regexp: "^opcache.memory_consumption"
        line: "opcache.memory_consumption = 96"
        state: present
   #   notify: restart apache

    - name: Usun testowa baze mySQL.
      mysql_db: db=test state=absent

    - name: Stworz baze MySQL dla Wordpressa.
      mysql_db: "db={{ domain }} state=present"

    - name: Uwtorz uzytkownika bazy MySQL dla Wordpress.
      mysql_user:
        name: "{{ domain }}"
        password: "1234"
        priv: "{{ domain }}.*:ALL"
        host: localhost
        state: present

    - name: Pobierz instalator Composer.
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-installer.php
        mode: 0755

    - name: Uruchom instalator Composer.
      command: >
        php composer-installer.php
        chdir=/tmp
        creates=/usr/local/bin/composer

    - name: Przenies Composer do ogolnodostepnej lokacji.
      shell: >
        mv /tmp/composer.phar /usr/local/bin/composer
        creates=/usr/local/bin/composer

    - name: Sprawdz drush master branch.
      git:
        repo: https://github.com/drush-ops/drush.git
        dest: /opt/drush

    - name: Instalacja Drush z Composer.
      shell: >
        /usr/local/bin/composer install
        chdir=/opt/drush
        creates=/opt/drush/vendor/autoload.php

    - name: Stworz drush bin symlink.
      file:
        src: /opt/drush/drush
        dest: /usr/local/bin/drush
        state: link
 
    - name: Wordpress instalacja
      subversion: repo=http://core.svn.wordpress.org/tags/4.7 dest=/var/www/wordpress
      tags: wordpress

    - name: Wordpress instalacja pluginow
      subversion: repo=http://svn.wp-plugins.org/{{ item.name }}/{{ item.version }}/ dest=/var/www/wordpress/wp-content/plugins/{{ item.name }}
      tags: wp_plugins
      with_items:
        - {name: all-in-one-favicon, version: trunk}
        - {name: bulk-move, version: tags/0.9}
        - {name: captain-typekit, version: trunk}
        - {name: disqus-comment-system, version: tags/2.74}
        - {name: embedded-video-with-link, version: tags/4.1}
        - {name: feedburner-plugin, version: trunk}
        - {name: font-awesome, version: tags/3.1}
        - {name: google-analytics-for-wordpress, version: tags/4.3.3}
        - {name: intensedebate, version: tags/2.9.5}
        - {name: jquery-image-lazy-loading, version: tags/0.20}
        - {name: link-manager, version: trunk}
        - {name: mailchimp, version: tags/1.2.14}
        - {name: milestone, version: tags/1.0}
        - {name: order-categories, version: trunk}
        - {name: prev-next-keyboard-navigation, version: tags/0.6}
        - {name: rsvp, version: tags/1.7.0}
        - {name: syntaxhighlighter, version: trunk}
        - {name: twitter-blackbird-pie, version: tags/0.5.3}
        - {name: unfiltered-mu, version: trunk}
        - {name: w3-total-cache, version: tags/0.9.2.11}
        - {name: wordpress-importer, version: tags/0.6.1}
        - {name: wordpress-mu-domain-mapping, version: tags/0.5.4.3}
        - {name: wp-markdown, version: tags/1.2}
        - {name: wp-syntax, version: tags/1.0}
        - {name: segmentio, version: tags/0.5.6}
        #- {name: , version: }
        #- {name: stealth-login-page, version: tags/3.0.0}
        #- {name: limit-login-attempts, version: tags/1.7.1}

    - name: chown wp
      file: path=/var/www/wordpress recurse=yes owner=www-data group=www-data state=directory
      tags: wp_plugins

    - name: noop
      command: touch /dev/null
      tags: noop


  handlers:
    - name: Restart ssh
      action: service name=ssh state=restarted
      tags: common

